import type { Player, Registration, Pool, Match, Season, MatchMessage } from '../types';

export const mockCurrentUser: Player = {
  id: 'player-1',
  userId: 'user-1',
  name: 'John Mitchell',
  email: 'john.mitchell@example.com',
  phone: '0412 345 678',
  club: 'Perth Bowling Club',
  state: 'WA',
  division: 'div1',
  createdAt: '2026-04-01T00:00:00Z',
};

export const mockPlayers: Player[] = [
  mockCurrentUser,
  {
    id: 'player-2',
    userId: 'user-2',
    name: 'Gary Thompson',
    email: 'gary.t@example.com',
    phone: '0423 456 789',
    club: 'Fremantle Bowling Club',
    state: 'WA',
    division: 'div1',
    createdAt: '2026-04-02T00:00:00Z',
  },
  {
    id: 'player-3',
    userId: 'user-3',
    name: 'Robert Chen',
    email: 'r.chen@example.com',
    phone: '0434 567 890',
    club: 'Subiaco Bowling Club',
    state: 'WA',
    division: 'div1',
    createdAt: '2026-04-03T00:00:00Z',
  },
  {
    id: 'player-4',
    userId: 'user-4',
    name: 'David Walsh',
    email: 'd.walsh@example.com',
    phone: '0445 678 901',
    club: 'Claremont Bowling Club',
    state: 'WA',
    division: 'div1',
    createdAt: '2026-04-04T00:00:00Z',
  },
  {
    id: 'player-5',
    userId: 'user-5',
    name: 'Steve Hamilton',
    email: 's.hamilton@example.com',
    phone: '0456 789 012',
    club: 'Sydney Bowling Club',
    state: 'NSW',
    division: 'div2',
    createdAt: '2026-04-01T00:00:00Z',
  },
  {
    id: 'player-6',
    userId: 'user-6',
    name: 'Peter Davis',
    email: 'p.davis@example.com',
    phone: '0467 890 123',
    club: 'Melbourne Bowling Club',
    state: 'VIC',
    division: 'div2',
    createdAt: '2026-04-02T00:00:00Z',
  },
];

export const mockMessages: MatchMessage[] = [
  {
    id: 'msg-1',
    matchId: 'match-1',
    playerId: 'player-2',
    playerName: 'Gary Thompson',
    message: 'Hi John, when are you free to play? I can do any Saturday afternoon in September.',
    createdAt: '2026-09-01T10:00:00Z',
  },
  {
    id: 'msg-2',
    matchId: 'match-1',
    playerId: 'player-1',
    playerName: 'John Mitchell',
    message: "G'day Gary! How about Saturday 14th at 2pm? I'll be hosting at Perth Bowling Club, 42 Mill Street.",
    createdAt: '2026-09-01T14:30:00Z',
  },
  {
    id: 'msg-3',
    matchId: 'match-1',
    playerId: 'player-2',
    playerName: 'Gary Thompson',
    message: "Perfect, 14th works for me. See you there! What time should I arrive to warm up?",
    createdAt: '2026-09-01T16:00:00Z',
  },
];

export const mockMatches: Match[] = [
  {
    id: 'match-1',
    poolId: 'pool-1',
    round: 1,
    eventType: 'singles_div1',
    competitionType: 'pool',
    homePlayerId: 'player-1',
    homePlayer: mockPlayers[0],
    awayPlayerId: 'player-2',
    awayPlayer: mockPlayers[1],
    venue: 'Perth Bowling Club, 42 Mill Street, Perth WA',
    scheduledDate: '2026-09-14T14:00:00Z',
    status: 'scheduled',
    confirmedByLoser: false,
    messages: mockMessages,
  },
  {
    id: 'match-2',
    poolId: 'pool-1',
    round: 2,
    eventType: 'singles_div1',
    competitionType: 'pool',
    homePlayerId: 'player-3',
    homePlayer: mockPlayers[2],
    awayPlayerId: 'player-1',
    awayPlayer: mockPlayers[0],
    status: 'pending',
    confirmedByLoser: false,
    messages: [],
  },
  {
    id: 'match-3',
    poolId: 'pool-1',
    round: 3,
    eventType: 'singles_div1',
    competitionType: 'pool',
    homePlayerId: 'player-1',
    homePlayer: mockPlayers[0],
    awayPlayerId: 'player-4',
    awayPlayer: mockPlayers[3],
    status: 'pending',
    confirmedByLoser: false,
    messages: [],
  },
  {
    id: 'match-4',
    poolId: 'pool-1',
    round: 0,
    eventType: 'singles_div1',
    competitionType: 'pool',
    homePlayerId: 'player-2',
    homePlayer: mockPlayers[1],
    awayPlayerId: 'player-4',
    awayPlayer: mockPlayers[3],
    venue: 'Fremantle Bowling Club',
    status: 'played',
    homeScore: 25,
    awayScore: 18,
    winnerId: 'player-2',
    confirmedByLoser: true,
    messages: [],
  },
  {
    id: 'match-5',
    poolId: 'pool-1',
    round: 0,
    eventType: 'singles_div1',
    competitionType: 'pool',
    homePlayerId: 'player-3',
    homePlayer: mockPlayers[2],
    awayPlayerId: 'player-4',
    awayPlayer: mockPlayers[3],
    venue: 'Subiaco Bowling Club',
    status: 'played',
    homeScore: 21,
    awayScore: 14,
    winnerId: 'player-3',
    confirmedByLoser: true,
    messages: [],
  },
  {
    id: 'match-6',
    poolId: 'pool-1',
    round: 0,
    eventType: 'singles_div1',
    competitionType: 'pool',
    homePlayerId: 'player-2',
    homePlayer: mockPlayers[1],
    awayPlayerId: 'player-3',
    awayPlayer: mockPlayers[2],
    venue: 'Fremantle Bowling Club',
    status: 'played',
    homeScore: 19,
    awayScore: 22,
    winnerId: 'player-3',
    confirmedByLoser: true,
    messages: [],
  },
];

export const mockPool: Pool = {
  id: 'pool-1',
  eventType: 'singles_div1',
  region: 'Western Australia',
  season: '2026',
  players: [
    { poolId: 'pool-1', playerId: 'player-1', player: mockPlayers[0], points: 0, shotDiff: 0, position: 4, wins: 0, losses: 0, played: 0 },
    { poolId: 'pool-1', playerId: 'player-2', player: mockPlayers[1], points: 2, shotDiff: 14, position: 2, wins: 1, losses: 1, played: 2 },
    { poolId: 'pool-1', playerId: 'player-3', player: mockPlayers[2], points: 4, shotDiff: 10, position: 1, wins: 2, losses: 0, played: 2 },
    { poolId: 'pool-1', playerId: 'player-4', player: mockPlayers[3], points: 0, shotDiff: -24, position: 3, wins: 0, losses: 2, played: 2 },
  ],
};

export const mockRegistrations: Registration[] = [
  {
    id: 'reg-1',
    playerId: 'player-1',
    player: mockPlayers[0],
    eventType: 'singles_div1',
    paymentStatus: 'paid',
    season: '2026',
    createdAt: '2026-04-01T00:00:00Z',
  },
  {
    id: 'reg-2',
    playerId: 'player-2',
    player: mockPlayers[1],
    eventType: 'singles_div1',
    paymentStatus: 'paid',
    season: '2026',
    createdAt: '2026-04-02T00:00:00Z',
  },
  {
    id: 'reg-3',
    playerId: 'player-3',
    player: mockPlayers[2],
    eventType: 'singles_div1',
    paymentStatus: 'paid',
    season: '2026',
    createdAt: '2026-04-03T00:00:00Z',
  },
  {
    id: 'reg-4',
    playerId: 'player-4',
    player: mockPlayers[3],
    eventType: 'singles_div1',
    paymentStatus: 'paid',
    season: '2026',
    createdAt: '2026-04-04T00:00:00Z',
  },
  {
    id: 'reg-5',
    playerId: 'player-5',
    player: mockPlayers[4],
    eventType: 'singles_div2',
    paymentStatus: 'paid',
    season: '2026',
    createdAt: '2026-04-01T00:00:00Z',
  },
  {
    id: 'reg-6',
    playerId: 'player-6',
    player: mockPlayers[5],
    eventType: 'singles_div2',
    paymentStatus: 'pending',
    season: '2026',
    createdAt: '2026-04-02T00:00:00Z',
  },
];

export const mockSeason: Season = {
  id: 'season-2026',
  name: '2026 National Season',
  status: 'pool_stage',
  poolStart: '2026-09-01T00:00:00Z',
  poolEnd: '2026-10-15T00:00:00Z',
  knockoutStart: '2026-10-20T00:00:00Z',
  finalsDate: '2027-02-01T00:00:00Z',
};
